<a href="https://colab.research.google.com/github/ARADHYA299/ML-PROJECTS/blob/main/LSTMnlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q tensorflow

In [2]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
vocab_size = 500

In [7]:
one_hot_repr = [one_hot(words , vocab_size) for words in sent]
print(one_hot_repr)

[[73, 248, 176, 390], [73, 248, 176, 410], [73, 55, 176, 290], [396, 211, 452, 382, 263], [396, 211, 452, 382, 109], [325, 73, 256, 176, 415], [16, 490, 110, 382]]


In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length = 7
embedded_docs = pad_sequences(one_hot_repr , padding = 'pre' , maxlen = sent_length)
print(embedded_docs)

[[  0   0   0  73 248 176 390]
 [  0   0   0  73 248 176 410]
 [  0   0   0  73  55 176 290]
 [  0   0 396 211 452 382 263]
 [  0   0 396 211 452 382 109]
 [  0   0 325  73 256 176 415]
 [  0   0   0  16 490 110 382]]


In [19]:
model = Sequential()
model.add(Embedding(input_dim = 500, output_dim=10 , input_length = 7))
model.compile('adam' , 'mse')

In [24]:
model.predict(embedded_docs)
model.summary()

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step


Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (7, 7, 10)             │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
embedded_docs[0]

array([  0,   0,   0,  73, 248, 176, 390], dtype=int32)